apiVersion: v1
kind: Service
metadata: 
  name: mongo-db-service
  namespace: ecommerce
  labels: 
    app: mongo-db
spec: 
  selector: 
    app: mongo-db
  ports: 
    - name: mongo-db
      port: 27017
      targetPort: 27017
  clusterIP: None
  