apiVersion: v1
kind: Service
metadata:
  name: {{ include "orders.fullname" . }}-service
  labels:
    {{- include "orders.labels" . | nindent 4 }}
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "orders.selectorLabels" . | nindent 4 }}
